# Generated by Django 3.2.5 on 2023-09-22 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=300)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.university')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.IntegerField(default=None)),
                ('name', models.CharField(default=None, max_length=300)),
                ('summary', models.TextField(default=None)),
                ('url', models.CharField(default=None, max_length=300)),
                ('plag_score', models.IntegerField(default=None)),
                ('is_approved', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('contributors', models.ManyToManyField(blank=True, default=None, to='mainapp.Student')),
                ('tags', models.ManyToManyField(blank=True, default=None, to='mainapp.Tags')),
                ('univ', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.university')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default=None)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default=None)),
                ('project', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.project')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.student')),
            ],
        ),
    ]
