# Generated by Django 4.2.5 on 2023-09-23 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_student_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectid',
        ),
    ]
